name: semoton_front
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  flutter_map: ^6.1.0  # OpenStreetMap 사용
  geolocator: ^10.1.0  # 현재 위치 가져오기
  permission_handler: ^11.0.1  # 위치 권한 요청
  cupertino_icons: ^1.0.8
  image_picker: ^1.0.7 # 카메라 사진촬영 요청
  camera: ^0.11.1
  xml: ^5.3.1
  url_launcher: ^6.1.11
  http: ^1.3.0
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/character2/
    - assets/character1/
    - assets/building/grey/
    - assets/building/pink/
    - assets/building/red/
  uses-material-design: true

